version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/feito

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Run Feito
          command: |
            . venv/bin/activate
            export PULL_REQUEST_ID="$(echo $CIRCLE_PULL_REQUEST | grep -o -E '[0-9]+')"
            export REPOSITORY_NAME="${CIRCLE_PROJECT_REPONAME}"
            export REPOSITORY_USERNAME="${CIRCLE_PROJECT_USERNAME}"

            if [[ -n ${PULL_REQUEST_ID} ]]
            then
              feito
            fi

      - store_artifacts:
          path: test-reports
          destination: test-reports
